name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (format 1.2.3)
        required: true

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Create git tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ github.event.inputs.version }}",
              sha: context.sha
            })
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
      - name: Install wheel
        run: pip install wheel
      - name: Build dist
        run: python setup.py sdist bdist_wheel
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
